name: Java Selenium Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven' # or 'gradle' if using Gradle

    - name: Set up Chrome Driver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run Tests with Maven
      run: mvn test
      env:
        CHROME_BIN: /usr/bin/chromium-browser
        CHROME_DRIVER: /usr/bin/chromedriver

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always() # Upload even if tests fail
      with:
        name: test-reports
        path: target/surefire-reports/
